    <div class="admin__old">
        <div class="main-col" id="container">
        <div id="result"></div><br/>
            <div id="messages">
                <div class="messages">
                    <div class="message message-notice notice">
                        <div>
                            Make sure that data encoding in the file is consistent and saved in CSV (comma separated only) with supported encodings (UTF-8 or ANSI).
                        </div>
                    </div>
                </div>
            </div>           
            <div id="messages">
                <div class="messages">
                    <div class="message message-notice notice">
                        <div>
                            Note: Before import the product attribute sets please refere sample csv files.
                        </div>
                    </div>
                </div>
            </div>
        <div id="import_content"></div>
            <div class="entry-edit form-inline">
                <form method="post" action="<?php //echo $block->getUrl('*/*/import') ?>" id="import_edit_form" enctype="multipart/form-data">
            
                    <input name="form_key" type="hidden" value="<?php echo $block->getFormKey() ?>" />
            
                    <fieldset id="base_fieldset" class="fieldset admin__fieldset ">
                        <legend class="admin__legend legend">
                            <span>Import Products Attribute Sets Settings</span>
                        </legend><br>
                        <div class="admin__field field field-entity ">
                            <div class="admin__field-control control">
                            <label for="filename" class="label admin__field-label"><span>Select File to Import</span></label>
                            <input type="file" class="input-file required-entry _required" title="Select File to Import" value=""  name="filename" id="filename" >
                            </div>
                        </div>
                    </fieldset>
                <!--<button type="submit" id="import_attr" class="action- scalable"><span>Click on for Import</span></button>-->
                     <button id="import_attrset" type="button" class="action- scalable"><span>Click on For Import</span></button>
                </form>
            </div>
        </div>
    </div>
    <?php $import_url = $block->getUrl('*/*/importSet'); ?>

	<script type="text/javascript">
		require([
			'jquery'
		],
		function(jQuery) {
			var formkey = "<?php echo $block->getFormKey() ?>";
			var importurl = "<?php echo $import_url ?>";

			jQuery('#import_edit_form').on('click', '#import_attrset', function(event){
				var file = document.getElementById("filename");
				var formData = new FormData();
				formData.append("filename", file.files[0]);
				formData.append('form_key', formkey);
				var filename = jQuery('#filename').val();
				if(filename) {
					jQuery.ajax({
						url : importurl,
						showLoader:true,
						contentType: false,
						processData: false,
						data: formData,                         
						type: 'post',
						success: function(data){
							jQuery('#result').html(data);
						}
					});
				}else{
					alert("Please Upload File");
				}
			})
		}
		);
	</script>

