<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_CustomQuoteExtension
 * @author     Extension Team
 * @copyright  Copyright (c) 2021 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

/** @var $block \Bss\QuoteExtension\Block\QuoteExtension\View\Action */
?>
<?php // @codingStandardsIgnoreFile ?>

<?php if ($block->canMoveCheckout() && $block->isEnable()) : ?>
    <div class="primary quote-button">
        <a  title="<?= $block->escapeHtml(__('Move to Checkout')); ?>" class="action primary quote-submit quote-checkout">
            <span><?= $block->escapeHtml(__('Move to Checkout')); ?></span>
        </a>
    </div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "*": {
            "Bss_CustomQuoteExtension/js/quote-view/move-checkout": {}
        }
    }
</script>
